### ISSUE TITLE
Not showing when used with another extension

### ISSUE THREAD

**Issue by mrlucas** [alex2005git/my-reddit-companion#4]
I use the extension [con reddit link opener](https://addons.mozilla.org/en-US/firefox/addon/con-reddit-link-opener/?src=search) to open several tabs in the background at once so they are all loaded by the time I get to them.  However, none of those tabs have the reddit companion bar on them.  I realize this is an obscure use-case, but I'm trying to recreate my Chrome add-on setup in Firefox, and I'd really appreciate it if you could take a look!

**Comment by akalineskou** [comment]
I'll take a look

**Comment by akalineskou** [comment]
@mrlucas I've uploaded version 3.4.2 which adds the option to enable the reddit bar for tabs not opened by user interaction (ie clicking on it)
Enable it in the addon options in the `Misc` category -> `Enable bar for tabs not opened by user interaction`

Reopen this issue if you have any issues with it.

**Comment by mrlucas** [comment]
Works great, thanks so much!
